# Debugging configuration
monitor:
  name: debug 
  seed: 100
  overwrite: true

  logging:
    period: 1
    level: debug
    wandb:
      active: true

  checkpoint:
    period: 20
    keep_only: 3

  profiler:
    active: true
    wait: 1
    steps: 50

cluster:
  compile_model: false
  slurm:
    nodes: 1
    nb_gpus: 2
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

model:
  vocab_size: 32
  emb_dim: 64
  nb_heads: 2
  ffn_dim: 256
  nb_layers: 2

data:
  seq_len: 32
  batch_size: 16
  seed: 42
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
      parents: [X]
      alpha: 1e3
    - name: Z2
      state_dim: 4
      alpha: 1e3
    - name: Z3
      state_dim: 4
      alpha: 1e3
    - name: Z4
      state_dim: 4
      parents: [X, Z3]
      alpha: 1e3
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4]
      alpha: 1e-2

optim:
  steps: 100
