# Debugging configuration
monitor:
  name: multinodes
  dir: /private/home/vivc/logs/composition/debug
  seed: 100
  overwrite: true

  logging:
    period: 10
    wandb:
      active: false
      entity: vivc
      project: llm-wrapper
      name: debug

  checkpoint:
    period: 1000
    keep_only: 3

cluster:
  compile_model: false
  slurm:
    partition: scavenge
    mem: 16G
    nodes: 2
    nb_gpus: 8
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

model:
  vocab_size: 32
  emb_dim: 64
  nb_heads: 2
  ffn_dim: 256
  nb_layers: 2

data:
  seq_len: 32
  batch_size: 16
  seed: 42
  graph_seed: 0
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
      parents: [X]
      alpha: 1e3
    - name: Z2
      state_dim: 4
      alpha: 1e3
    - name: Z3
      state_dim: 4
      alpha: 1e3
    - name: Z4
      state_dim: 4
      parents: [X, Z3]
      alpha: 1e3
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4]
      alpha: 1e-2

optim:
  steps: 10000
