# this tests how well multiple nodes are disentangled when running default vs slow vs dead mode, with different X alphas, num nodes, emb dims
launcher:
  name: onfly
  overwrite: true
  log_dir: $HOME/logs/exp11_onfly/onfly_correction

  script: src.apps.gssm.train_onfly

  slurm:
    nodes: 1
    nb_gpus: 1
    mem: 16G
    partition: learnfair
    time: 240          # job time in minutes
    signal_time: 120  # alert time in seconds

  grid:
    model:
      emb_dim: [128, 256, 512]
    data:
      seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      seq_len: [512]
      gssm:
        nodes:
        # lower X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1}
          - {name: Z2, state_dim: 8, alpha: 1e-1}
          - {name: Z3, state_dim: 8, alpha: 1e-1}
          - {name: Z4, state_dim: 8, alpha: 1e-1}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-3, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2}
          - {name: Z2, state_dim: 64, alpha: 5e-2}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-3, observed: true}
        # higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1}
          - {name: Z2, state_dim: 8, alpha: 1e-1}
          - {name: Z3, state_dim: 8, alpha: 1e-1}
          - {name: Z4, state_dim: 8, alpha: 1e-1}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2}
          - {name: Z2, state_dim: 64, alpha: 5e-2}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 1e-2, observed: true}
        # even higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1}
          - {name: Z2, state_dim: 8, alpha: 1e-1}
          - {name: Z3, state_dim: 8, alpha: 1e-1}
          - {name: Z4, state_dim: 8, alpha: 1e-1}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 5e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2}
          - {name: Z2, state_dim: 64, alpha: 5e-2}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 5e-2, observed: true}
        # one more X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1}
          - {name: Z2, state_dim: 8, alpha: 1e-1}
          - {name: Z3, state_dim: 8, alpha: 1e-1}
          - {name: Z4, state_dim: 8, alpha: 1e-1}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-1, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2}
          - {name: Z2, state_dim: 64, alpha: 5e-2}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-1, observed: true}

        # all as before but now with slow nodes
        # lower X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-3, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-3, observed: true}
        # higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 1e-2, observed: true}
        # even higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 5e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 5e-2, observed: true}
        # one more X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-1, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-1, observed: true}

        # all as before but now with dead nodes
        # lower X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-3, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-3, observed: true}
        # higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 1e-2, observed: true}
        # even higher X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 5e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 5e-2, observed: true}
        # one more X alpha
        - - {name: Z1, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z2, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z3, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: Z4, state_dim: 8, alpha: 1e-1, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2,Z3,Z4], alpha: 2e-1, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: Z2, state_dim: 64, alpha: 5e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 2e-1, observed: true}

run_config:
  low_memory_hmm: false

  cluster:
    compile_model: true

  data:
    seq_len: 512
    batch_size: 64
    seed: 453942
    gssm:
      nodes:
      - {name: Z1, state_dim: 64, alpha: 7e-3, mode: slow}
      - {name: Z2, state_dim: 64, alpha: 7e-3}
      - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 5e-2, observed: true}

  model:
    emb_dim: 512
    nb_layers: 4
    block:
      nb_heads: 4

  optim:
    steps: 2000
    lr: 1e-3
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    logging:
      period: 30
      level: info

    profiler:
      active: true
      wait: 1
      steps: -1

    wandb:
      active: true
      project: exp11_onfly
