# First experiments:
# Debugging configuration

launcher:
  name: exp1_onfly_small_Z
  overwrite: true
  log_dir: $HOME/logs/exp1/onfly_small_Z_cosine

  script: src.apps.gssm.train_onfly

  slurm:
    nodes: 1
    nb_gpus: 2        # use torchrun, or slurm, for multi-gpu runs
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:
  cluster:
    compile_model: false  # You can compile on V100 or better GPU (I have P100, which do not allow for compilation)

  data:
    seq_len: 2048
    batch_size: 16  # set this as big as possible to saturate your gpu memory
    seed: 42
    gssm:
      nodes:
      - name: Z1
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z2
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z3
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z4
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: X
        state_dim: 32
        parents: [Z1, Z2, Z3, Z4]
        alpha: 1e-1

      nodes:
      - name: Z1
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z2
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z3
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z4
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z5
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z6
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z7
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: Z8
        state_dim: 4
        parents: [X]
        alpha: 1e-2
      - name: X
        state_dim: 64
        parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
        alpha: 1e-1

  model:
    vocab_size: 32
    emb_dim: 256
    nb_heads: 12
    nb_layers: 12
    vocab_size: 32

  optim:
    steps: 100
    lr: 1e-2
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    checkpoint:
      period: 20
      keep_only: 3

    logging:
      period: 1
      level: info

    profiler:
      active: true
      heavy: true
      wait: 1
      steps: 10

    wandb:
      active: true
