launcher:
  name: exp0
  overwrite: true
  log_dir: $HOME/logs/exp0/small

run_config:
  cluster:
    compile_model: false

  data:
    seq_len: 2048
    batch_size: 16
    seed: 42
    gssm:
      nodes:
      - name: Z1
        state_dim: 256
        parents: []
        alpha: 4e-3
      - name: X
        state_dim: 32
        parents: [Z1]
        alpha: 1e-3
        observed: true

  model:
    emb_dim: 256
    nb_layers: 4
    block:
      nb_heads: 4

  optim:
    steps: 1000
    lr: 1e-3
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    checkpoint:
      period: 200
      keep_only: 3

    logging:
      period: 1
      level: info

    profiler:
      active: true
      heavy: true
      wait: 1
      steps: 10

    wandb:
      active: true
