# Data configurations

one_node:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 256
      parents: [X]
      alpha: !TODO!
    - name: X
      state_dim: 32
      parents: [Z1]
      alpha: 1e-3
  sets:
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/one_node/trainset.h5
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/one_node/testset.h5

two_nodes:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 16
      parents: [X]
      alpha: !TODO!
    - name: Z2
      state_dim: 16
      parents: [X]
      alpha: !TODO!
    - name: X
      state_dim: 32
      parents: [Z1, Z2]
      alpha: 1e-3
  sets:
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/two_nodes/trainset.h5
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/two_nodes/testset.h5

four_nodes:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
      parents: [X]
      alpha: !TODO!
    - name: Z2
      state_dim: 4
      parents: [X]
      alpha: !TODO!
    - name: Z3
      state_dim: 4
      parents: [X]
      alpha: !TODO!
    - name: Z4
      state_dim: 4
      parents: [X]
      alpha: !TODO!
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4]
      alpha: 1e-3
  sets:
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/four_nodes/trainset.h5
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/four_nodes/testset.h5

eight_nodes:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: !TODO!
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/eight_nodes/trainset.h5
  - n_data: !TODO|
    path: $HOME/data/composition/exp2/eight_nodes/testset.h5
