# Run with the `difficulty` script
# python -m src.apps.gssm.difficulty src/apps/gssm/experiments/exp1_alpha.yaml
# Script to fit the pairs (alpha_X, alpha_Z) for the first experiment

one_node:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    min: 1e-3
    max: 1e1
    num: 20
  path: $HOME/logs/exp2/difficulty/one_node.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 256
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1]

two_nodes:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    min: 1e-3
    max: 1e1
    num: 20
  path: $HOME/logs/exp2/difficulty/two_nodes.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 16
      parents: [X]
    - name: Z2
      state_dim: 16
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2]

four_nodes:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    min: 1e-3
    max: 1e1
    num: 20
  path: $HOME/logs/exp2/difficulty/four_nodes.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
      parents: [X]
    - name: Z2
      state_dim: 4
      parents: [X]
    - name: Z3
      state_dim: 4
      parents: [X]
    - name: Z4
      state_dim: 4
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4]

eight_nodes:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    min: 1e-3
    max: 1e1
    num: 20
  path: $HOME/logs/exp2/difficulty/eight_nodes.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X]
    - name: Z3
      state_dim: 2
      parents: [X]
    - name: Z4
      state_dim: 2
      parents: [X]
    - name: Z5
      state_dim: 2
      parents: [X]
    - name: Z6
      state_dim: 2
      parents: [X]
    - name: Z7
      state_dim: 2
      parents: [X]
    - name: Z8
      state_dim: 2
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
