# Debugging configuration

configs_path: /private/home/vivc/code/composable-llm/src/apps/gssm/configs/experiment2/map_grid_id_gssm_config.jsonl

launcher:
  name: debug_entropy
  log_dir: /checkpoint/vivc/icml/logs/exp2/entropy
  overwrite: false
  copy_code: false

  script: src.apps.gssm.entropy

  slurm:
    partition: scavenge
    mem: 16G
    nodes: 1
    nb_gpus: 2        # use torchrun, or slurm, for multi-gpu runs
    time: 1440        # job time in minutes
    signal_time: 120  # alert time in seconds

run_config:
  data:
    path: placeholder
    n_data: 10_000
    batch_size: 10
    asynchronous: false