seq_len: 257
seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
chunk_size: 10_000
gssm:
  nodes:
        - - {name: Z1, state_dim: 32, alpha: 1e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 1e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 1.5e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 1.5e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 2e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 2e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 3e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 4e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 5e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 6e-2, mode: default}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        # mode slow
        - - {name: Z1, state_dim: 32, alpha: 3.25e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 3.25e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3.9e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 3.9e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4.55e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 4.55e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.2e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 5.2e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.85e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 5.85e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6.5e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 6.5e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 7.15e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 7.15e-2, mode: slow}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        # mode dead
        - - {name: Z1, state_dim: 32, alpha: 1.9e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 1.9e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 2.85e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 2.85e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3.8e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 3.8e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4.75e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 4.75e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.7e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 5.7e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6.65e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 6.65e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 7.6e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 7.6e-2, mode: dead}
          - {name: X, state_dim: 32, parents: [Z1,Z2], alpha: 2.5e-2, observed: true, kernel_type: fullrank}

        # larger X state dim
        - - {name: Z1, state_dim: 32, alpha: 1e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 1e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 1.5e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 1.5e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 2e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 2e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 3e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 4e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 5e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6e-2, mode: default}
          - {name: Z2, state_dim: 32, alpha: 6e-2, mode: default}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        # mode slow
        - - {name: Z1, state_dim: 32, alpha: 3.25e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 3.25e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3.9e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 3.9e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4.55e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 4.55e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.2e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 5.2e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.85e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 5.85e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6.5e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 6.5e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 7.15e-2, mode: slow}
          - {name: Z2, state_dim: 32, alpha: 7.15e-2, mode: slow}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        # mode dead
        - - {name: Z1, state_dim: 32, alpha: 1.9e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 1.9e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 2.85e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 2.85e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 3.8e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 3.8e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 4.75e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 4.75e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 5.7e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 5.7e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 6.65e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 6.65e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
        - - {name: Z1, state_dim: 32, alpha: 7.6e-2, mode: dead}
          - {name: Z2, state_dim: 32, alpha: 7.6e-2, mode: dead}
          - {name: X, state_dim: 128, parents: [Z1,Z2], alpha: 6e-3, observed: true, kernel_type: fullrank}
          

sets:
- n_data: 100_000
  path: /checkpoint/$USER/datasets/icml/exp16/$GRIDID/trainset.h5
- n_data: 10_000
  path: /checkpoint/$USER/datasets/icml/exp16/$GRIDID/testset.h5
