easy:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp3/easy/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp3/easy/testset.h5

medium:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
      alpha: 1.25e-1
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z4
      state_dim: 2
      parents: [X, Z3]
      alpha: 1.25e-1
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z6
      state_dim: 2
      parents: [X, Z5]
      alpha: 1.25e-1
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z8
      state_dim: 2
      parents: [X, Z7]
      alpha: 1.25e-1
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp3/medium/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp3/medium/testset.h5

hard:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
      alpha: 1.25e-1
    - name: Z3
      state_dim: 2
      parents: [X, Z2]
      alpha: 1.25e-1
    - name: Z4
      state_dim: 2
      parents: [X, Z3]
      alpha: 1.25e-1
    - name: Z5
      state_dim: 2
      parents: [X, Z4]
      alpha: 1.25e-1
    - name: Z6
      state_dim: 2
      parents: [X, Z5]
      alpha: 1.25e-1
    - name: Z7
      state_dim: 2
      parents: [X, Z6]
      alpha: 1.25e-1
    - name: Z8
      state_dim: 2
      parents: [X, Z7]
      alpha: 1.25e-1
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp3/hard/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp3/hard/testset.h5

dense:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 1.25e-1
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
      alpha: 1.25e-1
    - name: Z3
      state_dim: 2
      parents: [X, Z1, Z2]
      alpha: 1.25e-1
    - name: Z4
      state_dim: 2
      parents: [X, Z1, Z2, Z3]
      alpha: 1.25e-1
    - name: Z5
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4]
      alpha: 1.25e-1
    - name: Z6
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5]
      alpha: 1.25e-1
    - name: Z7
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5, Z6]
      alpha: 1.25e-1
    - name: Z8
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5, Z6, Z7]
      alpha: 1.25e-1
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp3/dense/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp3/dense/testset.h5
