easy:
  seq_len: 2048
  seeds: [0, 1, 2, 3, 4, 5]
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 20
    min: 1e-3
    max: 1e1
  path: $HOME/logs/exp3/difficulty/easy.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
    - name: Z2
      state_dim: 4
    - name: Z3
      state_dim: 4
    - name: Z4
      state_dim: 4
    - name: Z5
      state_dim: 4
    - name: Z6
      state_dim: 4
    - name: Z7
      state_dim: 4
    - name: Z8
      state_dim: 4
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      observed: true

medium:
  seq_len: 2048
  seeds: [0, 1, 2, 3, 4, 5]
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 20
    min: 1e-3
    max: 1e1
  path: $HOME/logs/exp3/difficulty/medium.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
    - name: Z2
      state_dim: 4
      parents: [Z1]
    - name: Z3
      state_dim: 4
    - name: Z4
      state_dim: 4
      parents: [Z3]
    - name: Z5
      state_dim: 4
    - name: Z6
      state_dim: 4
      parents: [Z5]
    - name: Z7
      state_dim: 4
    - name: Z8
      state_dim: 4
      parents: [Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      observed: true

hard:
  seq_len: 2048
  seeds: [0, 1, 2, 3, 4, 5]
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 20
    min: 1e-3
    max: 1e1
  path: $HOME/logs/exp3/difficulty/hard.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
    - name: Z2
      state_dim: 4
      parents: [Z1]
    - name: Z3
      state_dim: 4
      parents: [Z2]
    - name: Z4
      state_dim: 4
      parents: [Z3]
    - name: Z5
      state_dim: 4
      parents: [Z4]
    - name: Z6
      state_dim: 4
      parents: [Z5]
    - name: Z7
      state_dim: 4
      parents: [Z6]
    - name: Z8
      state_dim: 4
      parents: [Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      observed: true

dense:
  seq_len: 2048
  seeds: [0, 1, 2, 3, 4, 5]
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 20
    min: 1e-3
    max: 1e1
  path: $HOME/logs/exp3/difficulty/dense.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 4
    - name: Z2
      state_dim: 4
      parents: [Z1]
    - name: Z3
      state_dim: 4
      parents: [Z1, Z2]
    - name: Z4
      state_dim: 4
      parents: [Z1, Z2, Z3]
    - name: Z5
      state_dim: 4
      parents: [Z1, Z2, Z3, Z4]
    - name: Z6
      state_dim: 4
      parents: [Z1, Z2, Z3, Z4, Z5]
    - name: Z7
      state_dim: 4
      parents: [Z1, Z2, Z3, Z4, Z5, Z6]
    - name: Z8
      state_dim: 4
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      observed: true
