launcher:
  name: onfly_dense
  overwrite: true
  log_dir: $HOME/logs/exp3/onfly_dense

  script: src.apps.gssm.train_onfly

  slurm:
    nodes: 1
    nb_gpus: 8
    mem: 16G
    partition: scavenge
    time: 120         # job time in minutes
    signal_time: 120  # alert time in seconds

  grid:
    model:
      emb_dim: [8, 16, 24, 32, 48, 64, 80, 96]
    data:
      seed: [42]
      # seed: [42, 0, 1, 2, 3, 4, 5, 6, 7]
    orchestration:
      utils:
        seed: [0, 1, 2, 3, 4, 5, 6, 7, 8]

run_config:
  cluster:
    compile_model: true

  data:
    seq_len: 2048
    batch_size: 16
    seed: 42
    gssm:
      nodes:
      - name: Z1
        state_dim: 2
        parents: [X]
        alpha: 1.25e-1
      - name: Z2
        state_dim: 2
        parents: [X, Z1]
        alpha: 1.25e-1
      - name: Z3
        state_dim: 2
        parents: [X, Z1, Z2]
        alpha: 1.25e-1
      - name: Z4
        state_dim: 2
        parents: [X, Z1, Z2, Z3]
        alpha: 1.25e-1
      - name: Z5
        state_dim: 2
        parents: [X, Z1, Z2, Z3, Z4]
        alpha: 1.25e-1
      - name: Z6
        state_dim: 2
        parents: [X, Z1, Z2, Z3, Z4, Z5]
        alpha: 1.25e-1
      - name: Z7
        state_dim: 2
        parents: [X, Z1, Z2, Z3, Z4, Z5, Z6]
        alpha: 1.25e-1
      - name: Z8
        state_dim: 2
        parents: [X, Z1, Z2, Z3, Z4, Z5, Z6, Z7]
        alpha: 1.25e-1
      - name: X
        state_dim: 32
        parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
        alpha: 1e-3

  model:
    emb_dim: 64
    nb_heads: 4
    nb_layers: 4

  optim:
    steps: 10000
    lr: 1e-2
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    logging:
      period: 1
      level: info

    profiler:
      active: true
      wait: 1
      steps: -1

    wandb:
      active: true
      project: exp3
