# Data configurations
# The outer keys for the different entry could be anything
# The inner keys should respect the same structure

debug:
  seq_len: 2048
  seed: 42
  batch_size: 128
  alpha_X:
    num: 10
    min: 1e-3
    max: 1e-1
  alpha_Z:
    min: 1e-3
    max: 1e1
    num: 20
  path: $HOME/logs/debug/difficulty/debug.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 256
      parents: []
    - name: Z2
      state_dim: 512
      parents: []
    - name: X
      state_dim: 256
      parents: [Z1, Z2]
      observed: True