# Debugging configuration

launcher:
  name: debug_entropy
  log_dir: $HOME/logs/exp1/0
  overwrite: false
  copy_code: false

  script: src.apps.gssm.entropy

  slurm:
    partition: scavenge
    mem: 16G
    nodes: 1
    nb_gpus: 2        # use torchrun, or slurm, for multi-gpu runs
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:
  data:
    path: /checkpoint/vivc/datasets/icml/exp1/0/testset.h5
    n_data: 1_000
    batch_size: 128
    asynchronous: false

  gssm:
    seed: 0
    batch_size: FAKE
    seq_len: FAKE
    gssm:
      nodes: 
      - {name: Z1, state_dim: 64, alpha: 1e-3}
      - {name: X, state_dim: 32, parents: [Z1], "alpha": 1e-3, "observed": true}
