# Debugging configuration

launcher:
  name: debug_eval
  log_dir: $HOME/logs/debug/evals/0/000000100
  overwrite: false
  copy_code: false

  script: src.apps.gssm.evaluation

  slurm:
    partition: scavenge
    mem: 16G
    nodes: 1
    nb_gpus: 1        # use torchrun, or slurm, for multi-gpu runs
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:

  cluster:
    compile_model: false  # You can compile on V100 or better GPU (I have P100, which do not allow for compilation)

  data:
    path: $HOME/data/composition/debug/testset.h5
    n_data: 1_000
    batch_size: 128

  model:
    vocab_size: 256
    emb_dim: 64
    nb_layers: 2
    block:
      seq_len: 2048
      nb_heads: 2
      hidden_dim: 256

  orchestration:
    parent_dir: $HOME/logs/debug/
    task_id: 0
    train_step: 100

    utils:
      seed: 100

    logging:
      period: 1
      level: debug
    wandb:
      active: false

    profiler:
      active: true
      wait: 1
      steps: -1
