# Debugging configuration

launcher:
  name: debug
  overwrite: true
  log_dir: $HOME/logs/debug

  script: src.apps.gssm.train

  slurm:
    partition: scavenge
    mem: 16G
    nodes: 1
    nb_gpus: 2        # use torchrun, or slurm, for multi-gpu runs
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:
  cluster:
    compile_model: false  # You can compile on V100 or better GPU (I have P100, which do not allow for compilation)

  data:
    path: $HOME/data/composition/debug/trainset.h5
    n_data: 1_000
    batch_size: 128
    seed: 42

  model:
    vocab_size: 256
    # emb_dim: 64
    # nb_layers: 2
    # block:
    #   seq_len: 2048
    #   nb_heads: 2
    #   hidden_dim: 256

    implementation: mamba
    emb_dim: 256
    nb_layers: 2
    block:
      nb_heads: 8
      state_dim: 64
      conv_size: 4

    # implementation: mingru
    # emb_dim: 256
    # nb_layers: 2
    # block:
    #   nb_heads: 8
    #   conv_size: null


  optim:
    steps: 100
    lr: 1e-2
    weight_decay: 0.1
    warmup: 15
    lr_min_ratio: 0

  orchestration:
    utils:
      seed: 100

    checkpoint:
      period: 20
      keep_only: 3

    logging:
      period: 1
      level: debug
    wandb:
      active: false

    profiler:
      active: true
      wait: 1
      steps: -1

  evaluation:
    period: 15
    asynchronous: false
    data:
      path: $HOME/data/composition/debug/testset.h5
      n_data: 100
      batch_size: 16
