launcher:
  name: onfly_small_Z
  overwrite: true
  log_dir: $HOME/logs/exp1/onfly_small_Z

  script: src.apps.gssm.train_onfly

  slurm:
    nodes: 1
    nb_gpus: 8
    time: 1440        # job time in minutes
    signal_time: 120  # alert time in seconds

  grid:
    model:
      emb_dim: [36, 72, 144, 288]
      nb_heads: [2, 4, 8, 12]
      nb_layers: [2, 4, 8, 12]

    optim:
      lr: [1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2, 1e-1]

run_config:
  cluster:
    compile_model: true

  data:
    seq_len: 2048
    batch_size: 16
    seed: 42
    gssm:
      nodes:
      - name: Z1
        state_dim: 4
        parents: [X]
        alpha: 1e-3
      - name: Z2
        state_dim: 4
        parents: [X]
        alpha: 1e-3
      - name: Z3
        state_dim: 4
        parents: [X]
        alpha: 1e-3
      - name: Z4
        state_dim: 4
        parents: [X]
        alpha: 1e-3
      - name: X
        state_dim: 32
        parents: [Z1, Z2, Z3, Z4]
        alpha: 5e-2

  model:
    emb_dim: 288
    nb_heads: 12
    nb_layers: 12

  optim:
    steps: 1000
    lr: 1e-2
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    checkpoint:
      period: 100
      keep_only: 3

    logging:
      period: 1
      level: info

    profiler:
      active: true
      wait: 1
      steps: -1

    wandb:
      active: true
      project: exp1
