# Debugging configuration
monitor:
  dir: "/private/home/vivc/dump/debug"

model:
  vocab_size: 4
  emb_dim: 64
  nb_heads: 2
  ffn_dim: 256
  nb_layers: 2

data:
  seq_len: 32
  batch_size: 32
  seed: 42

optim:
  steps: 100

checkpoint:
  freq: 10
  keep_only: 3