# Debugging configuration
monitor:
  overwrite: true

cluster:
  time: 1
  signal_time: 10

model:
  vocab_size: 4
  emb_dim: 64
  nb_heads: 2
  ffn_dim: 256
  nb_layers: 2

data:
  seq_len: 32
  batch_size: 32
  seed: 42

optim:
  steps: 10000

checkpoint:
  period: 10
  keep_only: 3