seq_len: 257
seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
chunk_size: 10_000
gssm:
  nodes:
  - - {name: Z1, state_dim: 256, alpha: 1e-4}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 256, alpha: 3e-4}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 192, alpha: 3e-4}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 192, alpha: 1e-3}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 128, alpha: 1e-3}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 128, alpha: 3e-3}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 92, alpha: 3e-3}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 92, alpha: 1e-2}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 64, alpha: 1e-2}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
  - - {name: Z1, state_dim: 64, alpha: 3e-2}
    - {name: X, state_dim:  8, parents: [Z1], alpha: 1e-1, observed: true}
    
sets:
- n_data: 100_000
  path: /checkpoint/$USER/datasets/icml/exp9/$GRIDID/trainset.h5
- n_data: 10_000
  path: /checkpoint/$USER/datasets/icml/exp9/$GRIDID/testset.h5
