launcher:
  name: onfly
  overwrite: true
  log_dir: $HOME/logs/exp9_onfly/onfly

  script: src.apps.gssm.train_onfly

  slurm:
    nodes: 1
    nb_gpus: 1
    mem: 16G
    partition: learnfair
    time: 120          # job time in minutes
    signal_time: 120  # alert time in seconds

  grid:
    model:
      emb_dim: [128]
    data:
      seed: [0, 1, 2, 3, 4]
      seq_len: [256]
      gssm:
        nodes:
        - - {name: Z1, state_dim: 256, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 256, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 192, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 192, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 128, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 128, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 92, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 92, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}
        - - {name: Z1, state_dim: 256, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 256, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 192, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 192, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 128, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 128, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 92, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 92, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 3e-4}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
        - - {name: Z1, state_dim: 64, alpha: 1e-3}
          - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-2, observed: true}
          

run_config:
  cluster:
    compile_model: true

  data:
    seq_len: 256
    batch_size: 64
    seed: 4894829
    gssm:
      nodes:
      - {name: Z1, state_dim: 256, alpha: 1e-3}
      - {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}

  model:
    emb_dim: 128
    nb_layers: 4
    block:
      nb_heads: 4

  optim:
    steps: 2000
    lr: 1e-3
    weight_decay: 0
    scheduler: constant

  orchestration:
    utils:
      seed: 100

    logging:
      period: 30
      level: info

    profiler:
      active: true
      wait: 1
      steps: -1

    wandb:
      active: true
      project: exp9_onfly
