seq_len: 257
seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
chunk_size: 10_000
gssm:
  nodes:
  - [{name: Z1, state_dim: 16, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 24, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 32, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 48, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 80, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 128, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 16, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 24, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 32, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 48, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 64, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 80, parents: [Z1], alpha: 1e-1, observed: true}]
  - [{name: Z1, state_dim: 64, alpha: 1e-1}, {name: X, state_dim: 128, parents: [Z1], alpha: 1e-1, observed: true}]
sets:
- n_data: 1_000_000
  path: /checkpoint/$USER/datasets/icml/exp5/$GRIDID/trainset.h5
- n_data: 10_000
  path: /checkpoint/$USER/datasets/icml/exp5/$GRIDID/testset.h5
