seq_len: 2049
seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
chunk_size: 10_000
gssm:
  nodes:
  - - {name: Z1, state_dim: 4, alpha: 1e-3}
    - {name: Z2, state_dim: 4, alpha: 1e-3}
    - {name: Z3, state_dim: 4, alpha: 1e-3}
    - {name: Z4, state_dim: 4, alpha: 1e-3}
    - {name: Z5, state_dim: 4, alpha: 1e-3}
    - {name: Z6, state_dim: 4, alpha: 1e-3}
    - {name: Z7, state_dim: 4, alpha: 1e-3}
    - {name: Z8, state_dim: 4, alpha: 1e-3}
    - {name: X, state_dim: 64, parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8], alpha: 1e-3, observed: true}
  - - {name: Z1, state_dim: 4, alpha: 1e-3}
    - {name: Z2, state_dim: 4, alpha: 1e-3, parents: [Z1]}
    - {name: Z3, state_dim: 4, alpha: 1e-3}
    - {name: Z4, state_dim: 4, alpha: 1e-3, parents: [Z3]}
    - {name: Z5, state_dim: 4, alpha: 1e-3}
    - {name: Z6, state_dim: 4, alpha: 1e-3, parents: [Z5]}
    - {name: Z7, state_dim: 4, alpha: 1e-3}
    - {name: Z8, state_dim: 4, alpha: 1e-3, parents: [Z7]}
    - {name: X, state_dim: 64, parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8], alpha: 1e-3, observed: true}
  - - {name: Z1, state_dim: 4, alpha: 1e-3}
    - {name: Z2, state_dim: 4, alpha: 1e-3, parents: [Z1]}
    - {name: Z3, state_dim: 4, alpha: 1e-3, parents: [Z2]}
    - {name: Z4, state_dim: 4, alpha: 1e-3, parents: [Z3]}
    - {name: Z5, state_dim: 4, alpha: 1e-3, parents: [Z4]}
    - {name: Z6, state_dim: 4, alpha: 1e-3, parents: [Z5]}
    - {name: Z7, state_dim: 4, alpha: 1e-3, parents: [Z6]}
    - {name: Z8, state_dim: 4, alpha: 1e-3, parents: [Z7]}
    - {name: X, state_dim: 64, parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8], alpha: 1e-3, observed: true}
  - - {name: Z1, state_dim: 4, alpha: 1e-3}
    - {name: Z2, state_dim: 4, alpha: 1e-3, parents: [Z1]}
    - {name: Z3, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2]}
    - {name: Z4, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2, Z3]}
    - {name: Z5, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2, Z3, Z4]}
    - {name: Z6, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2, Z3, Z4, Z5]}
    - {name: Z7, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2, Z3, Z4, Z5, Z6]}
    - {name: Z8, state_dim: 4, alpha: 1e-3, parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7]}
    - {name: X, state_dim: 64, parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8], alpha: 1e-3, observed: true}
sets:
- n_data: 1_000_000
  path: /checkpoint/vivc/datasets/icml/exp7/$GRIDID/trainset.h5
- n_data: 10_000
  path: /checkpoint/vivc/datasets/icml/exp7/$GRIDID/testset.h5
