# Debugging configuration

configs_path: $CODE_DIR/src/apps/gssm/configs/experiment7/map_grid_id_gssm_config.jsonl

launcher:
  name: entropy
  log_dir: /checkpoint/$USER/icml/logs/exp7/entropy
  overwrite: false
  copy_code: false

  script: src.apps.gssm.entropy

  slurm:
    partition: scavenge
    mem: 16G
    nodes: 1
    nb_gpus: 1        # use torchrun, or slurm, for multi-gpu runs
    time: 1440        # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:
  data:
    path: placeholder
    n_data: 10_000
    batch_size: 1_000
    asynchronous: false
