# Script to fit the pairs (alpha_X, alpha_Z) for the first experiment
# Run with the `difficulty` script
# python -m src.apps.gssm.difficulty <path to this file>

easy:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 2.5e-1
  path: $HOME/logs/exp3/difficulty/easy.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X]
    - name: Z3
      state_dim: 2
      parents: [X]
    - name: Z4
      state_dim: 2
      parents: [X]
    - name: Z5
      state_dim: 2
      parents: [X]
    - name: Z6
      state_dim: 2
      parents: [X]
    - name: Z7
      state_dim: 2
      parents: [X]
    - name: Z8
      state_dim: 2
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

medium:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 2.5e-1
  path: $HOME/logs/exp3/difficulty/medium.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
    - name: Z3
      state_dim: 2
      parents: [X]
    - name: Z4
      state_dim: 2
      parents: [X, Z3]
    - name: Z5
      state_dim: 2
      parents: [X]
    - name: Z6
      state_dim: 2
      parents: [X, Z5]
    - name: Z7
      state_dim: 2
      parents: [X]
    - name: Z8
      state_dim: 2
      parents: [X, Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

hard:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 2.5e-1
  path: $HOME/logs/exp3/difficulty/hard.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
    - name: Z3
      state_dim: 2
      parents: [X, Z2]
    - name: Z4
      state_dim: 2
      parents: [X, Z3]
    - name: Z5
      state_dim: 2
      parents: [X, Z4]
    - name: Z6
      state_dim: 2
      parents: [X, Z5]
    - name: Z7
      state_dim: 2
      parents: [X, Z6]
    - name: Z8
      state_dim: 2
      parents: [X, Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

dense:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 2.5e-1
  path: $HOME/logs/exp3/difficulty/dense.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X, Z1]
    - name: Z3
      state_dim: 2
      parents: [X, Z1, Z2]
    - name: Z4
      state_dim: 2
      parents: [X, Z1, Z2, Z3]
    - name: Z5
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4]
    - name: Z6
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5]
    - name: Z7
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5, Z6]
    - name: Z8
      state_dim: 2
      parents: [X, Z1, Z2, Z3, Z4, Z5, Z6, Z7]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
