base:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: 1.27e-1
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp4/base/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp4/base/testset.h5

slow:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: 0.345
      mode: slow
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp4/slow/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp4/slow/testset.h5

dead:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: 0.395
      mode: dead
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp4/dead/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp4/dead/testset.h5

context:
  seq_len: 2048
  seed: 42
  chunk_size: 10_000
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      alpha: 0.07
      mode: context
    - name: Z2
      state_dim: 2
      parents: [X]
      alpha: 0.07
      mode: context
    - name: Z3
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: Z4
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: Z5
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: Z6
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: Z7
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: Z8
      state_dim: 2
      parents: [X]
      alpha: 0.07
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]
      alpha: 1e-3
  sets:
  - n_data: 100_000
    path: $HOME/data/composition/exp4/dense/trainset.h5
  - n_data: 10_000
    path: $HOME/data/composition/exp4/dense/testset.h5
