# Script to fit the pairs (alpha_X, alpha_Z) for the first experiment
# Run with the `difficulty` script
# python -m src.apps.gssm.difficulty <path to this file>

base:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 2.67e-1
  path: $HOME/logs/exp4/difficulty/base.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
    - name: Z2
      state_dim: 2
      parents: [X]
    - name: Z3
      state_dim: 2
      parents: [X]
    - name: Z4
      state_dim: 2
      parents: [X]
    - name: Z5
      state_dim: 2
      parents: [X]
    - name: Z6
      state_dim: 2
      parents: [X]
    - name: Z7
      state_dim: 2
      parents: [X]
    - name: Z8
      state_dim: 2
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

slow:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 10
    min: 3.4e-1
    max: 3.5e-1
  path: $HOME/logs/exp4/difficulty/slow.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z2
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z3
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z4
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z5
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z6
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z7
      state_dim: 2
      parents: [X]
      mode: slow
    - name: Z8
      state_dim: 2
      parents: [X]
      mode: slow
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

dead:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 3.95e-1
  path: $HOME/logs/exp4/difficulty/dead.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z2
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z3
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z4
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z5
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z6
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z7
      state_dim: 2
      parents: [X]
      mode: dead
    - name: Z8
      state_dim: 2
      parents: [X]
      mode: dead
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]

context:
  seq_len: 2048
  seed: 42
  batch_size: 1024
  alpha_X:
    num: 1
    min: 1e-3
  alpha_Z:
    num: 1
    min: 7e-2
  path: $HOME/logs/exp4/difficulty/context.jsonl
  gssm:
    nodes:
    - name: Z1
      state_dim: 2
      parents: [X]
      mode: context
    - name: Z2
      state_dim: 2
      parents: [X]
      mode: context
    - name: Z3
      state_dim: 2
      parents: [X]
    - name: Z4
      state_dim: 2
      parents: [X]
    - name: Z5
      state_dim: 2
      parents: [X]
    - name: Z6
      state_dim: 2
      parents: [X]
    - name: Z7
      state_dim: 2
      parents: [X]
    - name: Z8
      state_dim: 2
      parents: [X]
    - name: X
      state_dim: 32
      parents: [Z1, Z2, Z3, Z4, Z5, Z6, Z7, Z8]